development:
  adapter: sqlite3
  database: db/development.sqlite

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  # database: mission
  # username: username
  # password: password
  # host: localhost
